version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: deploy/web.docker
        volumes:
            - ./:/var/www
        ports:
            - "10086:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: deploy/app.docker
        volumes:
            - ./:/var/www
        links:
            - database
            - cache
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
    database:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=homestead
            - MYSQL_USER=root
            - MYSQL_PASSWORD=secret
        ports:
            - "33061:3306"
        volumes:
            - ./deploy/dbdata:/var/lib/mysql
        restart: always
    cache:
        image: redis:5.0
        volumes:
            - ./deploy/cachedata:/data
        entrypoint: redis-server --appendonly yes
        restart: always
        ports:
            - "63791:6379"